export const environment = {
  production: true,
  name: "production",
  baseUrl: "https://orange-portfolio-5uas.onrender.com/",
  apiAuthenticate: "login",
  apiUsers: "users",
  apiProjects: "projects",
  apiTags: "projects/tags",
  getApiUserId: (id: string) => `users/${id}`,
  getApiUsersByName: (name: string) => `users/name/${name}`,
  getApiProjectId: (id: string) => `projects/${id}`,
  getApiProjectUserId: (id: string) => `projects/user/${id}`,
  getApiUpdatePassword: (id: string) => `users/${id}/password`,
  getApiIsGoogleLogin: (id:string) => `users/${id}/google`,
  apiKey: "orangeportfolio",
};
