export const preSelectedTags: string[] = [
  "UI/UX Design",
  "Design gráfico",
  "Modelagem 3D",
  "Arte Vetorial",
  "Arte Digital",
  "Programação",
  "Arquitetura",
  "Layout",
  "Card",
  "Wireframe",
  "Prototipagem",
  "Design Responsivo",
  "Paleta de Cores",
  "Tipografia",
  "Grid Layout",
  "Ícones",
  "Fotografia",
  "Ilustração",
  "Animação UI",
  "Design de Produto",
  "Branding",
  "Identidade Visual",
];
